
KNEE_JOINT_STEP_ANGLE_FRONT = 45
KNEE_JOINT_STEP_ANGLE_BACK = 45
KNEE_JOINT_STEP_ANGLE_INWARD = 45
KNEE_JOINT_STEP_ANGLE_OUTWARD = 45

HIP_JOINT_STEP_ANGLE_FRONT = 45
HIP_JOINT_STEP_ANGLE_BACK = 45
HIP_JOINT_STEP_ANGLE_INWARD = 45
HIP_JOINT_STEP_ANGLE_OUTWARD = 45

ANKLE_JOINT_STEP_ANGLE_FRONT = 45
ANKLE_JOINT_STEP_ANGLE_BACK = 45
ANKLE_JOINT_STEP_ANGLE_INWARD = 45
ANKLE_JOINT_STEP_ANGLE_OUTWARD = 45

FRONT_LEFT_ANKLE_JOINT_SERVO_INDEX = 0
FRONT_LEFT_KNEE_JOINT_SERVO_INDEX = 1
FRONT_LEFT_HIP_JOINT_SERVO_INDEX = 2

MID_LEFT_ANKLE_JOIN_SERVO_INDEX = 3
MID_LEFT_KNEE_JOIN_SERVO_INDEX = 3
MID_LEFT_HIP_JOIN_SERVO_INDEX = 3



REAR_LEFT_ANKLE_JOINT_SERVO_INDEX = 4
REAR_LEFT_KNEE_JOINT_SERVO_INDEX = 5
REAR_LEFT_HIP_JOINT_SERVO_INDEX = 6

FRONT_RIGHT_ANKLE_JOINT_SERVO_INDEX = 8
FRONT_RIGHT_KNEE_JOINT_SERVO_INDEX = 9
FRONT_RIGHT_HIP_JOINT_SERVO_INDEX = 10

REAR_RIGHT_ANKLE_JOINT_SERVO_INDEX = 12
REAR_RIGHT_KNEE_JOINT_SERVO_INDEX = 13
REAR_RIGHT_HIP_JOINT_SERVO_INDEX = 14

MID_RIGHT_ANKLE_JOIN_SERVO_INDEX = 3
MID_RIGHT_KNEE_JOIN_SERVO_INDEX = 3
MID_RIGHT_HIP_JOIN_SERVO_INDEX = 3

WALK_ANIMATION_DURATION_SECONDS = 0.5
RUN_ANIMATION_DURATION_SECONDS = 0.25
TURN_ANIMATION_DURATION_SECONDS = 1

COXA_LENGTH_MM = 43
FEMUR_LENGTH_MM = 60
TIBIA_LENGTH_MM = 104
COXA_Z_OFFSET_MM = 19

STANCE_HEIGHT_MM = 40

STEP_HEIGHT = 40   # How high to lift the leg (mm)
STEP_LENGTH = 50   # How far to step forward (mm)
NEUTRAL_Y = 70     # Your verified side-offset
NEUTRAL_Z = 130    # Your verified standing height
GAIT_SPEED = 3   # Adjust for MG995 speed limits

INIT_COORDINATES = (60, 60, 130)

TRIPOD_GATE_A_GROUP = [1, 3, 4] #FrontRight, BackRight, MiddleLeft